
name: mc2p
channels: 
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - scipy
  - scikit-image
  - scikit-learn
  - numpy
  - matplotlib 
  - torchvision
  - pytorch
  - jupyterlab
  - opencv
  - einops
  - pandas
